twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        global_categories: '@App\Service\CategoryService'
        global_articles:   '@App\Service\ArticleService'

when@test:
    twig:
        strict_variables: true
