version: '3.8'

services:
###> doctrine/doctrine-bundle ###
  php-fpm-env:
    container_name: php-apache
    image: php:7.4-fpm-alpine
    volumes:
    - ./php/src:
  database:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=blog
      - MYSQL_USER=root
  web:
    build: .
    ports:
      - 8080:

      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
