<?php

namespace App\Tests\Service;

use App\Service\ArticleService;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;

class ArticleServiceTest extends KernelTestCase
{
    private $articleService;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        self::bootKernel();

        $this->articleService = static::getContainer()->get(ArticleService::class);
    }


    public function testGetArticlesCount(): void
    {
        $articlesCount  = $this->articleService->getArticlesCount();

        $this->assertEquals(31, $articlesCount);
    }

    public function testGetArticlesPerFirstPage(): void
    {
        $articles = $this->articleService->getArticlesPerPage(1, 3);

        $this->assertEquals(3, count($articles));
    }

    public function testGetArticlesPerLastPage(): void
    {
        $articles = $this->articleService->getArticlesPerPage(11, 3);

        $this->assertEquals(1, count($articles));
    }
}
