<?php

namespace App\Tests\Functional\Service;

use App\Repository\ArticleRepository;
use App\Service\ArticleService;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;

class ArticleServiceFunctionalTest extends KernelTestCase
{

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        self::bootKernel();

        $this->articleService = static::getContainer()->get(ArticleService::class);
    }

    public function testGetArticlesPerPage(): void
    {
        $articles = $this->articleService->getArticlesPerPage(1, 3);

        $this->assertLessThanOrEqual(3, count($articles));
    }

    public function testIncreaseViewsOfArticle(): void
    {
        $articleRepo      = static::getContainer()->get(ArticleRepository::class);
        $article          = $articleRepo->find(125);
        $previousViews    = $article->getViews();

        $this->articleService->increaseViews($article);

        $article        = $articleRepo->find(125);
        $newViews       = $article->getViews();
        $expectedViews  = $previousViews+1;

        $this->assertEquals($expectedViews, $newViews);
    }
}