<?php

namespace App\Tests\Functional\Service;

use App\Repository\ArticleRepository;
use App\Service\ArticleService;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;

class ArticleServiceFunctionalTest extends KernelTestCase
{

    private $articleService;
    private $articleRepo;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        self::bootKernel();

        $this->articleService = static::getContainer()->get(ArticleService::class);
        $this->articleRepo      = static::getContainer()->get(ArticleRepository::class);
    }

    public function testIncreaseViewsOfArticle(): void
    {
        // Arrange
        $article          = $this->articleRepo->find(125);
        $previousViews    = $article->getViews();

        // Act
        $this->articleService->increaseViews($article);
        $article        = $this->articleRepo->find(125);

        // Assert
        $this->assertEquals($previousViews+1, $article->getViews());
    }
}